spring:
  application:
    name: checkout-payment-gateway

bank:
  simulator:
    base-url: http://localhost:8080

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true